### PR TITLE
Testing/7.61.1

### PR DESCRIPTION
**Pull request by uilianries**

### CODE REVIEW

**Comment by SSE4** [comment]
@Croydon so, what's the conclusion? should I merge these PRs or not?

**Comment by Croydon** [comment]
I think it's odd that we use different OpenSSL versions on different platforms and I would like to unify this. WDYT?

**Comment by SSE4** [comment]
@Croydon I agree, but your explanation above mentions that there are problems with OpenSSL 1.1.1 and cross-building. if there are problems with it, may be you could create an issue in `conan-community` repository so I can take a look and fix? at least, I was able to cross-build OpenSSL into Android, iOS and Emscripten.

**Comment by Croydon** [comment]
@SSE4 According to @theirix there are cross-platform building issues with OpenSSL < 1.1.1, but NOT with 1.1.1

**Comment by SSE4** [comment]
@theirix may you create an issue(s) in conan-community then?
if `OpenSSL 1.1.1` has no issues with cross-building, let's just use it everywhere

**Comment by Croydon** [comment]
We need to check which of these changes needs to be applied to `testing/7.64.1`

**Comment by uilianries** [comment]
I think it's a good opportunity since we have many PRs.

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
