### PR TITLE
WIP, TEST CI: Improved autotools build after Conan 1.3

### PR DESCRIPTION
**Pull request by danimtb**
We mead some improvements after Conan 1.3 in the AutoTools build helper and used this package as an example to test the improvements.

I did the changes some days ago and want to test first if everything goes OK in the CI.

Please note that your testing branch is behind stable and the diff is a bit unreadable 😢

### CODE REVIEW

**Comment by theirix** [comment]
Thanks for a refactoring and bringing modern Conan changes!
I reviewed all proposed changes and merged them as small commits into the "develop" branch - testing/7.52.1. Reworked args passing so it builds fine now.

In addition, I made a workaround for an error in pre-7.56.0 that previously needed a custom `make_suffix`. Now the ugly fix is gone.

A question - are you sure we can remove customizing `host` and `build` for mingw? Is the mingw cross-compiling really addressed in Conan now?

**Comment by danimtb** [comment]
@theirix  AutoTools build helper also calculates the cross-building flags automatically so it should work with MinGW. It uses [tools.get_gnu_triplet()](https://docs.conan.io/en/latest/reference/tools.html#tools-get-gnu-triplet) to do so and of course you can still set those flags manually.

I have to check why the CI is failing though... 😥

**Comment by theirix** [comment]
@danimtb oh, good to hear it! I'll check it in the next build.

> I have to check why the CI is failing though... 

With my additional patches in testing/7.52.1 it does not fail anymore.

**Comment by danimtb** [comment]
ok, so just tell me what should I do with this PR. As you already merged the changes to your branch, should I close it?

**Comment by theirix** [comment]
Yes, we can close it.

I'll merge changes from my branch to stable a little later, after testing mingw.

**Comment by danimtb** [comment]
Great! thanks for taking care 👍 Ping me if you need any help!

**Comment by theirix** [comment]
@danimtb finally checked your proposal about mingw - ac69c2f80e771988f6a459ee9e8bed36d8e910fc. It works perfectly! I think we can drop all these `--build=x86_64-w64-mingw32` from recipes.

**Comment by danimtb** [comment]
great news @theirix! We'll keep working on simplifying the recipes 👍

**Pull request closed without merging**
