### PR TITLE
Linux ARM cross build support (7.56.1)

### PR DESCRIPTION
**Pull request by lasote**
Same than previous but for the newer version. I'm ok only with this one.

### CODE REVIEW

**Review by uilianries — APPROVED** [review]
Looks really nice!

I'll add ARM job to run this feature on CI.

**Review by uilianries — APPROVED** [review]
Looks really nice!

I'll add ARM job to run this feature on CI.

**Review by theirix — APPROVED** [review]
Looks good! Refactoring is very important for such complex recipes.

**Comment by theirix** [comment]
@uilianries , good idea, let's try to add an ARM job before merging to stable. Will it be a publishing build (arm packages)?

**Comment by uilianries** [comment]
Yeah, thanks to @lasote. He created Docker images with cross-compiler. I'll update ASAP

**Pull request merged**
